homewebserverstuff/audiobuch/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.audiobView, name='audiob_home'),
    path('autor/', views.authors_home, name='authors_home'),
    path('autor/neu/', views.new_author, name='author_new'),
    path('autor/<int:pk>/', views.authorDetailView.as_view(), name='author_details'),
    path('autor/<int:pk>/del/', views.authorDeleteView.as_view(), name='author_delete'),
    path('autor/<int:pk>/edit/', views.authorUpdateView.as_view(), name='author_edit'),
    path('hörbuch/neu/', views.new_audiobook, name='audiob_new'),
    path('hörbuch/<int:pk>/', views.audiobDetailView.as_view(), name='audiob_details'),
]

homewebserverstuff/homewebserver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from legacyPWM import views as legacy_views
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', legacy_views.legacyManager, name="legacy_manager"),
    path('termine/', include('termine.urls')),
    path("jsi18n", JavaScriptCatalog.as_view(), name="js-catalog"),
    path('hörbücher/', include('audiobuch.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homewebserverstuff/termine/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.termineView, name='termine_home'),
    path('<int:pk>/', views.terminDetailView.as_view(), name='termine_details'),
    path('neu/', views.new_termin, name='termine_new'),
    path('<int:pk>/del', views.terminDeleteView.as_view(), name='termine_delete'),
]

homewebserverstuff/audiobuch/models.py
from django.db import models
from django.urls import reverse


# author.audiobook_set <-> audiobook.authors
# audiobook.va_set <-> va.audiobooks
# role.vas <-> va.role_set
# role.audiobooks <-> audiobook.role_set
# audiobook.altName_set <-> altName.audiobook


class author(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    name_first = models.CharField(max_length=100, blank=True, null=True)
    name_mids = models.CharField(max_length=300, blank=True, null=True)
    name_last = models.CharField(max_length=100)
    aliases = models.CharField(max_length=500, blank=True, null=True)
    birth = models.DateField(blank=True, null=True)
    death = models.DateField(blank=True, null=True)
    alive = models.BooleanField(default=False)
    anzeige_name = models.CharField(max_length=300, blank=True, null=True)
    remarks = models.TextField(blank=True)

    class Meta:
        ordering = ["anzeige_name", "birth"]

    def __str__(self):
        if self.anzeige_name:
            return self.anzeige_name
        else:
            full_name = (((self.title + " ") if self.title else "")
                        + ((self.name_first + " ") if self.name_first else "")
                        + ((self.name_mids + " ") if self.name_mids else "")
                        + self.name_last)
            return full_name

    def get_absolute_url(self):
        return reverse("author_details", kwargs={"pk": self.pk})


class audiobook(models.Model):
    authors = models.ManyToManyField(author)
    name = models.CharField(max_length=300)
    release_book = models.DateField(blank=True, null=True)
    release_book_germany = models.DateField(blank=True, null=True)
    release_as_audio = models.DateField(blank=True, null=True)
    synopsis = models.TextField(blank=True, null=True)
    ro_ss_choices = [
        ("ss", "Kurzgeschichte"),  # ss = short story
        ("ro", "Roman"),
    ]
    ro_ss = models.CharField(max_length=len(ro_ss_choices), choices=ro_ss_choices, default="ro", blank=False)
    shortened = models.BooleanField(default=False)
    boxset = models.BooleanField(default=False)
    boxset_name = models.CharField(max_length=100, blank=True, null=True)
    mp3CD = models.BooleanField(default=False)
    digital_only = models.BooleanField(default=False)
    amount_CDs = models.PositiveIntegerField()
    genre = models.CharField(max_length=150)
    comments = models.TextField(blank=True, null=True)
    runtime = models.PositiveIntegerField()

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "audiobücher"

    def __str__(self):
        return self.name


class va(models.Model):  # Voice Actor
    audiobooks = models.ManyToManyField(audiobook)
    title = models.CharField(max_length=100, blank=True, null=True)
    name_first = models.CharField(max_length=100, blank=True, null=True)
    name_mids = models.CharField(max_length=300, blank=True, null=True)
    name_last = models.CharField(max_length=100)

    class Meta:
        ordering = ["name_last", "name_first"]
        verbose_name = "voice actor"
        verbose_name_plural = "voice actors"

    def __str__(self):
        full_name = (((self.title + " ") if self.title else "")
                    + ((self.name_first + " ") if self.name_first else "")
                    + ((self.name_mids + " ") if self.name_mids else "")
                    + self.name_last)
        return full_name


class role(models.Model):
    audiobooks = models.ManyToManyField(audiobook)
    vas = models.ManyToManyField(va)  # Voice ActorS
    title = models.CharField(max_length=100, blank=True, null=True)
    name_first = models.CharField(max_length=100, blank=True, null=True)
    name_mids = models.CharField(max_length=300, blank=True, null=True)
    name_last = models.CharField(max_length=100)

    class Meta:
        ordering = ["name_last", "name_first"]

    def __str__(self):
        full_name = (((self.title + " ") if self.title else "")
                    + ((self.name_first + " ") if self.name_first else "")
                    + ((self.name_mids + " ") if self.name_mids else "")
                    + self.name_last)
        return full_name


class altName(models.Model):
    audiobook = models.ForeignKey(audiobook, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    comment = models.TextField(blank=True, null=True)

homewebserverstuff/audiobuch/forms.py
from django import forms
from .models import author, audiobook


class author_form(forms.ModelForm):
    class Meta:
        model = author
        fields = ["title", "name_first", "name_mids", "name_last", "aliases", "birth", "death", "alive", "anzeige_name", "remarks"]
        widgets = {
            "title": forms.TextInput(
                attrs={"placeholder": "Titel", "aria-label": "title"}
            ),
            "name_first": forms.TextInput(
                attrs={"placeholder": "Vorname", "aria-label": "name_first"}
            ),
            "name_mids": forms.TextInput(
                attrs={"placeholder": "Zweitnamen", "aria-label": "name_mids"}
            ),
            "name_last": forms.TextInput(
                attrs={"placeholder": "Nachname", "aria-label": "name_last"}
            ),
            "aliases": forms.TextInput(
                attrs={"placeholder": "Aliase", "aria-label": "aliases"}
            ),
            "anzeige_name": forms.TextInput(
                attrs={"placeholder": "Anzeige Name", "aria-label": "anzeige_name"}
            ),
            "remarks": forms.Textarea(
                attrs={"placeholder": "Anmerkungen", "aria-label": "remarks", "rows": "5"}
            ),
        }

    def save(self, commit=True):
        model = super().save(commit=False)
        if not self.cleaned_data["anzeige_name"]:
            model.anzeige_name = ""
            if self.cleaned_data["name_first"]:
                model.anzeige_name = f"{str(self.cleaned_data['name_first'])} "
            model.anzeige_name += str(self.cleaned_data["name_last"])
        if commit:
            model.save()

        return model


class audiobook_form(forms.ModelForm):
    class Meta:
        model = audiobook
        fields = ["authors", "name", "release_book",
                  "release_book_germany", "release_as_audio", "synopsis",
                  "ro_ss", "shortened", "boxset", "boxset_name", "mp3CD",
                  "digital_only", "amount_CDs", "genre", "comments", "runtime"]
        widgets = {
            "authors": forms.SelectMultiple(
                attrs={"aria-label": "authors", "size": "10"}
            ),
            "name": forms.TextInput(
                attrs={"placeholder": "Name", "aria-label": "name"}
            ),
            "synopsis": forms.Textarea(
                attrs={"placeholder": "Synopsis", "aria-label": "synopsis", "rows": "5"}
            ),
            "boxset_name": forms.TextInput(
                attrs={"placeholder": "Boxset Name", "aria-label": "boxset_name", "disabled": "disabled"}
            ),
            "genre": forms.TextInput(
                attrs={"placeholder": "Genre", "aria-label": "genre"}
            ),
            "comments": forms.Textarea(
                attrs={"placeholder": "Kommentare", "aria-label": "comments", "rows": "5"}
            ),
        }

homewebserverstuff/audiobuch/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import author_form, audiobook_form
from .models import audiobook as audiobook_model
from .models import author as author_model


def authors_home(request):
    context = {}
    context["request"] = request
    pagination_page = request.GET.get("page", 1)
    filterBy = request.GET.get("filterBy", None)
    filterValue = request.GET.get("filterValue", None)
    if filterBy and filterValue:
        filterBy = filterBy.lower()
        context["filterBy"] = filterBy
        context["filterValue"] = filterValue
        if filterBy == "title":
            authors = author_model.objects.filter(title=f"{filterValue}")
        elif filterBy == "vorname":
            authors = author_model.objects.filter(name_first=f"{filterValue}")
        elif filterBy == "zweitname":
            authors = author_model.objects.filter(name_mids__contains=f"{filterValue}")
        elif filterBy == "nachname":
            authors = author_model.objects.filter(name_last=f"{filterValue}")
        elif filterBy == "alias":
            authors = author_model.objects.filter(aliases__contains=f"{filterValue}")
        elif filterBy == "anzeigename":
            authors = author_model.objects.filter(anzeige_name__contains=f"{filterValue}")
    else:
        authors = author_model.objects.all()

    paginator = Paginator(authors, 10)
    try:
        context["authors"] = paginator.page(pagination_page)
    except PageNotAnInteger:
        messages.warning(request, "Das page-attribut akzeptiert nur Ints!")
        context["authors"] = paginator.page(1)
    except EmptyPage:
        messages.info(request, "Diese Seitenzahl existiert nicht.")
        context["authors"] = paginator.page(paginator.num_pages)

    return render(request, "audiobuch/authors.html", context)


def new_author(request):
    if request.method == "POST":
        author = author_form(request.POST)
        if author.is_valid():
            author.save()
            messages.success(request, "Autor erstellt.")
            return redirect('authors_home')
        else:
            messages.error(request, "Ein Fehler ist aufgetreten.")
            print(request.POST)
    else:
        author = author_form()

    return render(request, "audiobuch/new_author.html", {"author": author})


class authorDetailView(DetailView):
    model = author_model
    template_name = "audiobuch/details_author.html"
    context_object_name = "author"


class authorUpdateView(UpdateView):
    model = author_model
    template_name = "audiobuch/edit_author.html"
    context_object_name = "author"
    fields = ["title", "name_first", "name_mids", "name_last", "aliases", "birth", "death", "alive", "anzeige_name", "remarks"]

    def form_valid(self, form):
        if not form.instance.anzeige_name:
            anzeige_name = ""
            if form.instance.name_first:
                anzeige_name = f"{ str(form.instance.name_first) } "
            anzeige_name += str(form.instance.name_last)
            form.instance.anzeige_name = anzeige_name
        return super().form_valid(form)


class authorDeleteView(SuccessMessageMixin, DeleteView):
    model = author_model
    template_name = "audiobuch/delete_author.html"
    context_object_name = "author"
    success_url = reverse_lazy("authors_home")
    success_message = "Autor erfolgreich gelöscht."

    # success_message alone doesn't work for DeleteViews
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(authorDeleteView, self).delete(request, *args, **kwargs)


def audiobView(request):
    context = {}
    context["audiobooks"] = audiobook_model.objects.all()

    return render(request, "audiobuch/audiob.html", context)


class audiobDetailView(DetailView):
    model = audiobook_model
    template_name = "audiobuch/details_audiob.html"
    context_object_name = "audiobook"


def new_audiobook(request):
    if request.method == "POST":
        audiobook = audiobook_form(request.POST)
        if audiobook.is_valid():
            audiobook.save()
            messages.success(request, "Audiobuch-Eintrag erstellt.")
            return redirect('audiob_home')
        else:
            messages.error(request, "Ein Fehler ist aufgetreten")
            print(request.POST)
    else:
        audiobook = audiobook_form()

    return render(request, "audiobuch/new_audiob.html", {"audiobook": audiobook})

homewebserverstuff/audiobuch/templates/audiobuch/audiob.html
{% extends "legacyPWM/base.html" %}
{% block header %}
    <title>
        {% if filterBy %}
            Gefilterte Hörbücher
        {% else %}
            Alle Hörbücher
        {% endif %}
    </title>
{% endblock header %}

{% block body %}
    <main class="ext-container audiob-main-content">
        <h1>hier kommmt hörbuch kram hin!</h1>
        {% for audiobook in audiobooks %}
            <p><a style="color:pink;" href="{% url 'audiob_details' audiobook.id %}">{{ audiobook }}</a></p>
        {% endfor %}

        <a class="termine-a-as-btn" href="{% url 'authors_home' %}">Zu Autoren</a>
        <a class="termine-a-as-btn" href="{% url 'audiob_new' %}">Neues Hörbuch</a>
        <!-- TODO: zu autor-übersicht -->
        <!-- TODO: hörbücher hinzufügen -->
    </main>
{% endblock body %}

homewebserverstuff/audiobuch/templates/audiobuch/authors.html
{% extends "legacyPWM/base.html" %}
{% load pagination_extras %}
{% block header %}
    <title>
        {% if filterBy %}
            Gefilterte Autoren
        {% else %}
            Alle Autoren
        {% endif %}
    </title>
{% endblock header %}

{% block body %}
    <main class="ext-container audiob-authors-content">
        <h1>Autoren</h1>
        {% if filterBy and filterValue %}
        <h2>{{ filterBy }} : {{ filterValue }}</h2>
        {% endif %}
        <h2></h2>
        <div class="termine-terminliste">
            {% for author in authors %}
                <a href="{% url 'author_details' author.id %}"> {{ author }} </a>
            {% endfor %}
        </div>
        {% if authors.paginator.num_pages > 1 %}
            <div class="pagination">
                {% if authors.has_previous %}
                    <a class="pagination-a-as-btn" href="{% replace_add_get_key_value request 'page' 1 %}"><<</a>
                    <a class="pagination-a-as-btn" href="{% replace_add_get_key_value request 'page' authors.previous_page_number %}"><</a>
                {% endif %}
                {% for i in authors.paginator.page_range %}
                    {% if i == authors.number %}
                        <a class="pagination-a-as-btn current-page" href="{% replace_add_get_key_value request 'page' i %}">{{ i }}</a>
                    {% elif i > authors.number|add:'-3' and i < authors.number|add:'3' %}
                        <a class="pagination-a-as-btn" href="{% replace_add_get_key_value request 'page' i %}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
                {% if authors.has_next %}
                    <a class="pagination-a-as-btn" href="{% replace_add_get_key_value request 'page' authors.next_page_number %}">></a>
                    <a class="pagination-a-as-btn" href="{% replace_add_get_key_value request 'page' authors.paginator.num_pages %}">>></a>
                {% endif %}
            </div>
        {% endif %}
        <a class="termine-a-as-btn" href="{% url 'author_new' %}">Neuen Autor hinzufügen</a>
        <form method="GET">
            <div class="termine-filter-form">
                <div class="termine-filter-form-input">
                    <div class="termine-wrap-select">
                        <select id="filterBy" name="filterBy">
                            <option disabled selected hidden>Filter:</option>
                            <option value="title">Titel</option>
                            <option value="vorname">Vorname</option>
                            <option value="zweitname">Zweitname</option>
                            <option value="nachname">Nachname</option>
                            <option value="alias">Alias</option>
                            <option value="anzeigename">Angezeigter Name</option>
                        </select>
                    </div>
                    <div class="termine-wrap-input">
                        <input class="termine-inp" type="text" id="filterValue" name="filterValue" placeholder="Filter-Wert">
                    </div>
                </div>
                <button class="termine-filter-btn" type="submit">Filtern!</button>
            </div>
        </form>
    </main>
{% endblock body %}

homewebserverstuff/audiobuch/templates/audiobuch/delete_author.html
{% extends "legacyPWM/base.html" %}
{% block header %}
    <title>
        {{ author }} Löschen?
    </title>
{% endblock header %}

{% block body %}
    <main class="ext-container audiob-main-content"> <!-- TODO: change to audiob-authors-delete-content -->
        <h1>Autoren Löschung</h1>
        <form method="POST">
            {% csrf_token %}
            Sicher, dass "{{ author }}" gelöscht werden soll?
            <div class="termine-del-submits">
                <button class="termine-del-btn" type="submit">Löschen!</button>
                <a class="termine-a-as-btn termine-del-a-btn" href="{% url 'author_details' author.id %}">Abbrechen</a>
            </div>
        </form>
    </main>
{% endblock body %}

homewebserverstuff/audiobuch/templates/audiobuch/details_audiob.html
{% extends "legacyPWM/base.html" %}
{% block header %}
    <title>
        {{ audiobook }} Details
    </title>
{% endblock header %}

{% block body %}
    <main class="ext-container audiob-main-content"> <!-- TODO: change to audiob-authors-detail-content -->
        <h1>{{ audiobook }}</h1>
        <h2>Details</h2>
        <h3 style="padding:0;margin:0;">Autoren:</h3>
        {% for author in audiobook.authors.all %}
            <p style="padding-left:3em;">{{ author }}</p>
        {% endfor %}
        <h3 style="padding:0;margin:0;">Name:</h3>
        <p style="padding-left:3em;">{{ audiobook.name }}</p>
        <h3 style="padding:0;margin:0;">Erscheinungsdatum Buch (original):</h3>
        <p style="padding-left:3em;">{{ audiobook.release_book }}</p>
        <h3 style="padding:0;margin:0;">Erscheinungsdatum Buch (deutschland):</h3>
        <p style="padding-left:3em;">{{ audiobook.release_book_germany }}</p>
        <h3 style="padding:0;margin:0;">Erscheinungsdatum Hörbuch:</h3>
        <p style="padding-left:3em;">{{ audiobook.release_as_audio }}</p>
        <h3 style="padding:0;margin:0;">Synopsis</h3>
        <p style="padding-left:3em;">{{ audiobook.synopsis }}</p>
        <h3 style="padding:0;margin:0;">Typ:</h3>
        {% if audiobook.ro_ss == 'ro' %}
            <p style="padding-left:3em;">Roman</p>
        {% else %}
            <p style="padding-left:3em;">Kurzgeschichte</p>
        {% endif %}
        <h3 style="padding:0;margin:0;">Gekürzt?</h3>
        <p style="padding-left:3em;">{{ audiobook.shortened }}</p>
        <h3 style="padding:0;margin:0;">Teil eines Boxsets?</h3>
        <p style="padding-left:3em;">{{ audiobook.boxset }}</p>
        {% if audiobook.boxset %}
            <h3 style="padding:0;margin:0;">Boxset:</h3>
            <p style="padding-left:3em;">{{ audiobook.boxset_name }}</p>
        {% endif %}
        <h3 style="padding:0;margin:0;">Mp3 CD?</h3>
        <p style="padding-left:3em;">{{ audiobook.mp3CD }}</p>
        <h3 style="padding:0;margin:0;">Nur Digital?</h3>
        <p style="padding-left:3em;">{{ audiobook.digital_only }}</p>
        <h3 style="padding:0;margin:0;">CDs:</h3>
        <p style="padding-left:3em;">{{ audiobook.amount_CDs }}</p>
        <h3 style="padding:0;margin:0;">Genre:</h3>
        <p style="padding-left:3em;">{{ audiobook.genre }}</p>
        <h3 style="padding:0;margin:0;">Kommentare:</h3>
        <p style="padding-left:3em;">{{ audiobook.comments }}</p>
        <h3 style="padding:0;margin:0;">Laufzeit (in Minuten):</h3>
        <p style="padding-left:3em;">{{ audiobook.runtime }}</p>

        <a class="termine-a-as-btn termine-details-a-btn" href="{% url 'audiob_home' %}">Zurück</a>
    </main>
{% endblock body %}

homewebserverstuff/audiobuch/templates/audiobuch/edit_author.html
{% extends "legacyPWM/base.html" %}
{% block header %}
    <title>Bearbeite {{ author.anzeige_name }}</title>
{% endblock header %}

{% block body %}
    <main class="ext-container audiob-author-new-content">
        <h1>Autor Bearbeiten</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="blockify-django-auto-input">
                <input type="text" name="title" {% if author.title %}value="{{ author.title }}"{% endif %} maxlength="100" id="id_title">
                <label for="id_title">Titel</label>
            </div>
            <div class="blockify-django-auto-input">
                <input type="text" name="name_first" {% if author.name_first %}value="{{ author.name_first }}"{% endif %} maxlength="100" id="id_name_first">
                <label for="id_name_first">Vorname:</label>
            </div>
            <div class="blockify-django-auto-input">
                <input type="text" name="name_mids" {% if author.name_mids %}value="{{ author.name_mids }}"{% endif %} maxlength="300" id="id_name_mids">
                <label for="id_name_mids">Zweitnamen:</label>
            </div>
            <div class="blockify-django-auto-input">
                <input type="text" name="name_last" {% if author.name_last %}value="{{ author.name_last }}"{% endif %} maxlength="100" required id="id_name_last">
                <label for="id_name_last">Nachname:</label>
            </div>
            <div class="blockify-django-auto-input">
                <input type="text" name="aliases" {% if author.aliases %}value="{{ author.aliases }}"{% endif %} maxlength="500" id="id_aliases">
                <label for="id_aliases">Aliase</label>
            </div>
            <div class="blockify-django-auto-input">
                <input type="text" name="anzeige_name" {% if author.anzeige_name %}value="{{ author.anzeige_name }}"{% endif %} maxlength="300" id="id_anzeige_name">
                <label for="id_anzeige_name">Anzeige Name</label>
            </div>
            <div class="blockify-django-auto-input">
                <label for="id_birth">Geburtstag:</label>
                <input type="date" name="birth" id="id_birth" {% if author.birth %}value="{{ author.birth|date:"Y-m-d" }}"{% endif %}>
            </div>
            <div class="blockify-django-auto-input">
                <label for="id_death">Todestag:</label>
                <input type="date" name="death" id="id_death" {% if author.death %}value="{{ author.death|date:"Y-m-d" }}"{% endif %}>
            </div>
            <div class="blockify-django-auto-input">
                <label for="id_alive">Lebendig:</label><input type="checkbox" name="alive" id="id_alive" {% if author.alive %}checked{% endif %}>
            </div>
            <div class="blockify-django-auto-input">
                <label for="id_remarks">Anmerkungen:</label><br />
                <textarea name="remarks" cols="40" rows="5" placeholder="Keine Anmerkungen vorhanden." aria-label="remarks" id="id_remarks">{% if author.remarks %}{{ author.remarks }}{% endif %}</textarea>
            </div>

            <button class="author-create-btn" type="submit">Updaten!</button>
            <a class="termine-a-as-btn" href="{% url 'author_details' author.id %}">Zurück</a>
        </form>
    </main>
{% endblock body %}

homewebserverstuff/audiobuch/templates/audiobuch/new_audiob.html
{% extends "legacyPWM/base.html" %}
{% load static %}
{% block header %}
    <script defer src="{% static 'legacyPWM/new_audiobook.js' %}"></script>

    <title>Neues Hörbuch</title>
{% endblock header %}

{% block body %}
    <main class="ext-container audiob-audiob-new-content">
        <h1>Neues Hörbuch</h1>
        <form method="POST">
            {% csrf_token %}
            <p>{{ audiobook.authors }}</p>
            <p>{{ audiobook.name }}</p>
            <p>
                <label for="id_release_book">Erscheinungsdatum (Originales Buch):</label>
                <input type="date" name="release_book" id="id_release_book">
            </p>
            <p>
                <label for="id_release_book_germany">Erscheinungsdatum (Deutsche Fassung):</label>
                <input type="date" name="release_book_germany" id="id_release_book_germany">
            </p>
            <p>
                <label for="id_release_as_audio">Erscheinungsdatum (Audiobuch):</label>
                <input type="date" name="release_as_audio" id="id_release_as_audio">
            </p>
            <p>{{ audiobook.synopsis }}</p>
            <p><label for="id_ro_ss">Hörbuch Typ:</label>{{ audiobook.ro_ss }}</p>
            <p><label for="id_shortened">Gekürzt:</label>{{ audiobook.shortened }}</p>
            <p><label for="id_boxset">Teil eines Boxset:</label>{{ audiobook.boxset }}</p>
            <p>{{ audiobook.boxset_name }}</p>
            <p><label for="id_mp3CD">Mp3 CD:</label>{{ audiobook.mp3CD }}</p>
            <p><label for="id_digital_only">Nur Digital:</label>{{ audiobook.digital_only }}</p>
            <p><label for="id_amount_CDs">CDs</label>{{ audiobook.amount_CDs }}</p>
            <p>{{ audiobook.genre }}</p>
            <p>{{ audiobook.comments }}</p>
            <p><label for="id_runtime">Laufzeit</label>{{ audiobook.runtime }}</p>
            <button class="termine-create-btn" type="submit">Erstellen!</button>
        </form>
    </main>
{% endblock body %}

homewebserverstuff/audiobuch/templates/audiobuch/new_author.html
{% extends "legacyPWM/base.html" %}
{% block header %}
    <title>Neuer Autor</title>
{% endblock header %}

{% block body %}
    <main class="ext-container audiob-author-new-content">
        <h1>Neuer Autor</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="blockify-django-auto-input">
                {{ author.title }}
            </div>
            <div class="blockify-django-auto-input">
                {{ author.name_first }}
            </div>
            <div class="blockify-django-auto-input">
                {{ author.name_mids }}
            </div>
            <div class="blockify-django-auto-input">
                {{ author.name_last }}
            </div>
            <div class="blockify-django-auto-input">
                {{ author.aliases }}
            </div>
            <div class="blockify-django-auto-input">
                {{ author.anzeige_name }}
            </div>
            <div class="blockify-django-auto-input">
                {{ author.remarks }}
            </div>
            <div class="blockify-django-auto-input">
                <label for="id_birth">Geburtstag:</label>
                <input type="date" name="birth" id="id_birth">
            </div>
            <div class="blockify-django-auto-input">
                <label for="id_death">Todestag:</label>
                <input type="date" name="death" id="id_death">
            </div>
            <div class="blockify-django-auto-input">
                <label for="id_alive">Lebendig:</label>{{ author.alive }}
            </div>

            <button class="author-create-btn" type="submit">Erstellen!</button>
            <a class="termine-a-as-btn termine-details-a-btn" href="{% url 'authors_home' %}">Zurück</a>
        </form>
    </main>
{% endblock body %}

<!-- fields = ["title", "name_first", "name_mids", "name_last", "aliases", "birth", "death", "alive"] -->