homewebserverstuff/homewebserver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from legacyPWM import views as legacy_views
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', legacy_views.legacyManager, name="legacy_manager"),
    path('termine/', include('termine.urls')),
    path("jsi18n", JavaScriptCatalog.as_view(), name="js-catalog"),
    path('hörbücher/', include('audiobuch.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homewebserverstuff/termine/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.termineView, name='termine_home'),
    path('<int:pk>/', views.terminDetailView.as_view(), name='termine_details'),
    path('neu/', views.new_termin, name='termine_new'),
    path('<int:pk>/del', views.terminDeleteView.as_view(), name='termine_delete'),
]

homewebserverstuff/termine/models.py
from django.db import models
from django.utils.timezone import localtime as lt
from django.contrib.auth.models import User


class termin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    termin_name = models.CharField(max_length=100)
    date = models.DateTimeField()
    end = models.DateTimeField(blank=True, null=True)
    comment = models.TextField(blank=True)
    reminder = models.BooleanField(default=False)

    def __str__(self):
        return f"{lt(self.date).day:02d}.{lt(self.date).month:02d}.{lt(self.date).year:04d} "\
               f"{lt(self.date).hour:02d}:{lt(self.date).minute:02d} - "\
               f"{self.user.username} - "\
               f"{self.termin_name}"

    class Meta:
        ordering = ["-date", "user"]
        verbose_name_plural = "termine"


class user_additionals(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    discord_id = models.CharField(max_length=50, blank=True, null=True)  # CharField just in case discord ever decides to throw around leading 0s

homewebserverstuff/termine/forms.py
from django import forms
from .models import termin
from django.utils import timezone
from django.contrib.admin.widgets import AdminSplitDateTime


class termin_form(forms.ModelForm):
    sdt = forms.SplitDateTimeField(widget=AdminSplitDateTime)
    endsdt = forms.SplitDateTimeField(widget=AdminSplitDateTime, required=False)

    class Meta:
        model = termin
        fields = ["user", "termin_name", "comment", "reminder"]
        widgets = {
            "termin_name": forms.TextInput(
                attrs={"placeholder": "Termin Name"}
            ),
            "comment": forms.Textarea(
                attrs={"placeholder": "Termin Kommentar (optional)"}
            ),
        }

    def save(self, commit=True):
        model = super().save(commit=False)
        model.date = timezone.localtime(self.cleaned_data["sdt"])
        if self.cleaned_data["endsdt"]:
            model.end = timezone.localtime(self.cleaned_data["endsdt"])
        if commit:
            model.save()

        return model

homewebserverstuff/termine/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView
from .forms import termin_form
from .models import termin as termin_model


def termineView(request):
    context = {}
    filterBy = request.GET.get("filterBy", None)
    filterValue = request.GET.get("filterValue", None)
    if filterBy and filterValue:
        filterBy = filterBy.lower()
        context["filterBy"] = filterBy
        context["filterValue"] = filterValue
        if filterBy == "user":
            context["termine"] = termin_model.objects.filter(user__username=f"{filterValue}")
        elif filterBy == "termin_name":
            context["termine"] = termin_model.objects.filter(termin_name=f"{filterValue}")
    else:
        context["termine"] = termin_model.objects.all()

    return render(request, "termine/termine.html", context)


def new_termin(request):
    if request.method == "POST":
        termine = termin_form(request.POST)
        if termine.is_valid():
            termine.save()
            messages.success(request, "Termin wurde registriert.")
            return redirect('termine_home')
        else:
            messages.error(request, "Ein Fehler ist aufgetreten.")
            print(request.POST)
    else:
        termine = termin_form()

    return render(request, "termine/neu.html", {"termine": termine})


class terminDetailView(DetailView):
    model = termin_model
    template_name = "termine/details.html"
    context_object_name = "termin"


class terminDeleteView(SuccessMessageMixin, DeleteView):
    model = termin_model
    template_name = "termine/delete.html"
    context_object_name = "termin"
    success_url = reverse_lazy("termine_home")
    success_message = "Termin erfolgreich gelöscht."

    # success_message alone doesn't work for DeleteViews
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(terminDeleteView, self).delete(request, *args, **kwargs)

homewebserverstuff/termine/templates/termine/delete.html
{% extends "legacyPWM/base.html" %}
{% block header %}
    <title>
        {{ termin.termin_name }} Löschen?
    </title>
{% endblock header %}

{% block body %}
    <main class="ext-container termine-delete-content">
        <h1>Termin Löschung</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="termine-del-desciption">
                Sicher, dass der Termin<br>
                "{{ termin.termin_name }}"<br>
                {% if termin.end %}
                    vom<br>
                    {{ termin.date|date:"d.m.Y" }} um {{ termin.date|date:"H:i" }} Uhr<br>
                    bis zum<br>
                    {{ termin.end|date:"d.m.Y" }} um {{ termin.end|date:"H:i" }} Uhr<br>
                {% else %}
                    am<br>
                    {{ termin.date|date:"d.m.Y" }} um {{ termin.date|date:"H:i" }} Uhr<br>
                {% endif %}
                    gelöscht werden soll?
            </div>
            <div class="termine-del-submits">
                <button class="termine-del-btn" type="submit">Löschen!</button>
                <a class="termine-a-as-btn termine-del-a-btn" href="{% url 'termine_details' termin.id %}">Abbrechen</a>
            </div>
        </form>
    </main>
{% endblock body %}

homewebserverstuff/termine/templates/termine/details.html
{% extends "legacyPWM/base.html" %}
{% block header %}
    <title>
        {{ termin.termin_name }} Details
    </title>
{% endblock header %}

{% block body %}
    <main class="ext-container termine-details-content">
        <h1>{{ termin.termin_name }}</h1>
        <h2>Details</h2>
        <label>Für:</label><div class="termin-details-detail">{{ termin.user }}</div>
        <label>Beginnt:</label><div class="termin-details-detail">{{ termin.date|date:"d.m.Y" }} um {{ termin.date|date:"H:i" }} Uhr</div>
        {% if termin.end %}
            <label>Endet:</label><div class="termin-details-detail">{{ termin.end|date:"d.m.Y" }} um {{ termin.end|date:"H:i" }} Uhr</div>
        {% endif %}
        <label>Erinnerung:</label><div class="termin-details-detail">{% if termin.reminder %}Aktiv{% else %}Inaktiv{% endif %}</div>
        <label>Kommentar:</label><div class="termin-details-detail">{{ termin.comment }}</div>
        <a class="termine-a-as-btn termine-details-a-btn" href="{% url 'termine_home' %}">Zurück</a>
        <a class="termine-a-as-btn termine-details-a-btn" href="{% url 'termine_delete' termin.id %}">Löschen</a>
    </main>
{% endblock body %}

homewebserverstuff/termine/templates/termine/neu.html
{% extends "legacyPWM/base.html" %}
{% block header %}
    <title>Neuer Termin</title>
{% endblock header %}

{% block body %}
    <main class="ext-container termine-neu-content">
        <h1>Neuer Termin</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="termineu-block">
                <label for="id_user" class="termineu-label">Nutzer:</label>
                {{ termine.user }}
            </div>
            <div class="termineu-block">{{ termine.termin_name }}</div>
            <div class="termineu-block">{{ termine.comment }}</div>
            <div class="termineu-block">
                <label for="id_reminder" class="termineu-label">Erinnerung?</label>
                <input type="checkbox" id="id_reminder" name="reminder">
            </div>
            <div class="termineu-mininfo">---- Startdatum</div>
            <div class="termineu-block">
                <label for="id_sdt_0" class="termineu-label">Datum:</label>
                <input type="date" name="sdt_0" id="id_sdt_0" required>
            </div>
            <div class="termineu-block">
                <label for="id_sdt_1" class="termineu-label">Uhrzeit:</label>
                <div class="termineu-time-info"><input type="time" name="sdt_1" id="id_sdt_1" required></div>
            </div>
            <div class="termineu-mininfo">---- Enddatum (optional)</div>
            <div class="termineu-block">
                <label for="id_endsdt_0" class="termineu-label">Datum:</label>
                <input type="date" name="endsdt_0" id="id_endsdt_0">
            </div>
            <div class="termineu-block">
                <label for="id_endsdt_1" class="termineu-label">Uhrzeit:</label>
                <div class="termineu-time-info"><input type="time" name="endsdt_1" id="id_endsdt_1"></div>
            </div>
            <button class="termine-create-btn" type="submit">Erstellen!</button>
        </form>
    </main>
{% endblock body %}

homewebserverstuff/termine/templates/termine/termine.html
{% extends "legacyPWM/base.html" %}
{% block header %}
    <title>
        {% if filterBy %}
            Gefilterte Termine
        {% else %}
            Alle Termine
        {% endif %}
    </title>
{% endblock header %}

{% block body %}
    <main class="ext-container termine-main-content">
        <h1>Termine</h1>
        {% if filterBy %}
            <h2>{{ filterBy }}: {{ filterValue }}</h2>
        {% else %}
            <h2>Übersicht</h2>
        {% endif %}
        <div class="termine-terminliste">
            {% for termin in termine %}
                <a href="{% url 'termine_details' termin.id %}"> {{ termin }} </a>
            {% endfor %}
        </div>
        <a class="termine-a-as-btn" href="{% url 'termine_new' %}">Neuer Termin</a>
        <form method="GET">
            <div class="termine-filter-form">
                <div class="termine-filter-form-input">
                    <div class="termine-wrap-select">
                        <select id="filterBy" name="filterBy">
                            <option disabled selected hidden>Filter:</option>
                            <option value="user">Nutzername</option>
                            <option value="termin_name">Terminname</option>
                        </select>
                    </div>
                    <div class="termine-wrap-input">
                        <input class="termine-inp" type="text" id="filterValue" name="filterValue" placeholder="Nutzer- oder Terminname">
                    </div>
                </div>
                <button class="termine-filter-btn" type="submit">Filtern!</button>
            </div>
        </form>
    </main>
{% endblock body %}